import assert from "node:assert/strict"; import test from "node:test";
import { buildTenantMarketingBrain } from "./marketing-brain"; import { orchestrateGroundedContent } from "./marketing-content-orchestrator";
const objective={id:"o1",tenantId:"t1",name:"Leads",outcome:"Generate leads",targetMetric:"leads",targetValue:10,startsAt:"2026-10-08",endsAt:"2026-10-31"};
const campaign={id:"c1",tenantId:"t1",objectiveId:"o1",name:"Launch",audienceIds:["a1"],offeringIds:["off1"],status:"PLANNED" as const,startsAt:"2026-10-08",endsAt:"2026-10-31",actions:[{id:"act1",tenantId:"t1",campaignId:"c1",channel:"LINKEDIN",kind:"CONTENT_PREPARATION",status:"DRAFT" as const,idempotencyKey:"i1",correlationId:"corr"}],results:[],createdAt:"now",updatedAt:"now"};
const brain=buildTenantMarketingBrain({tenantId:"t1",brand:{tenantId:"t1",name:"HerreB",positioning:"AI consulting",voice:["direct"],prohibitedThemes:["unsupported guarantees"]},audiences:[{id:"a1",tenantId:"t1",name:"Owners",description:"Business owners",needs:["growth"],channels:["LINKEDIN"]}],offerings:[{id:"off1",tenantId:"t1",type:"SERVICE",name:"AI Consulting",active:true,metadata:{},description:"Consulting"}],knowledge:[{id:"k1",tenantId:"t1",namespace:"n",kind:"CANONICAL",subject:"offer",content:{},sourceRefs:["crm:offer"],verified:true,updatedAt:"now"}],claims:[{id:"cl1",tenantId:"t1",offeringId:"off1",text:"AI consulting is offered",sourceKnowledgeIds:["k1"],verified:true}]});
test("orchestrator supplies brand, audience, objective and only allowed claims, returning DRAFT",async()=>{let seen:unknown;const draft=await orchestrateGroundedContent({brain,campaign,objective,offeringId:"off1",audienceId:"a1",channel:"LINKEDIN",generator:{async generate(input){seen=input;return {headline:"AI Consulting",body:"Built for growth",claimIds:["cl1"]};}}});assert.ok(seen&&typeof seen==="object");const generatedInput=seen as {brandVoice:string[];prohibitedThemes:string[];objective:{targetMetric:string};allowedClaims:{id:string;text:string}[]};assert.deepEqual(generatedInput.brandVoice,["direct"]);assert.deepEqual(generatedInput.prohibitedThemes,["unsupported guarantees"]);assert.equal(generatedInput.objective.targetMetric,"leads");assert.deepEqual(generatedInput.allowedClaims,[{id:"cl1",text:"AI consulting is offered"}]);assert.equal(draft.status,"DRAFT");assert.deepEqual(draft.sourceKnowledgeIds,["k1"]);});
test("generator cannot inject an unverified claim",async()=>{await assert.rejects(()=>orchestrateGroundedContent({brain,campaign,objective,offeringId:"off1",audienceId:"a1",channel:"LINKEDIN",generator:{async generate(){return {headline:"h",body:"b",claimIds:["invented"]};}}}),/CONTENT_CLAIM_NOT_PUBLISHABLE:invented/);});
test("campaign lineage is enforced before generation",async()=>{let calls=0;await assert.rejects(()=>orchestrateGroundedContent({brain,campaign:{...campaign,audienceIds:["other"]},objective,offeringId:"off1",audienceId:"a1",channel:"LINKEDIN",generator:{async generate(){calls++;return {headline:"h",body:"b",claimIds:["cl1"]};}}}),/CONTENT_CAMPAIGN_AUDIENCE_MISMATCH/);assert.equal(calls,0);});
test("brand profile is required",async()=>{const noBrand={...brain,brand:undefined};await assert.rejects(()=>orchestrateGroundedContent({brain:noBrand,campaign,objective,offeringId:"off1",audienceId:"a1",channel:"LINKEDIN",generator:{async generate(){return {headline:"h",body:"b",claimIds:["cl1"]};}}}),/CONTENT_BRAND_PROFILE_REQUIRED/);});
